name: Deploy to chemmara.space

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create .htaccess
        run: |
          cat > ./build/.htaccess << EOL
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.html [L]
          </IfModule>

          # Enable GZIP compression
          <IfModule mod_deflate.c>
            AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css application/javascript application/json
          </IfModule>

          # Set caching headers
          <IfModule mod_expires.c>
            ExpiresActive On
            ExpiresByType image/jpg "access plus 1 year"
            ExpiresByType image/jpeg "access plus 1 year"
            ExpiresByType image/gif "access plus 1 year"
            ExpiresByType image/png "access plus 1 year"
            ExpiresByType image/svg+xml "access plus 1 year"
            ExpiresByType text/css "access plus 1 month"
            ExpiresByType application/javascript "access plus 1 month"
            ExpiresByType application/json "access plus 0 seconds"
            ExpiresByType text/html "access plus 0 seconds"
          </IfModule>
          EOL

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "build/"
          REMOTE_HOST: "chemmara.space"
          REMOTE_USER: "chemmara"
          TARGET: "/var/www/html"
          
      - name: Create deployment tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Deployed version ${{ github.ref_name }} to chemmara.space" > deployment.txt
          
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: deployment.txt
          name: Release ${{ github.ref_name }}
          body: |
            ## Deployment to chemmara.space
            
            This version has been automatically deployed to [chemmara.space](https://chemmara.space).
            
            ### Changes in this release:
            - See commit history for details